# Generated by Django 5.0.6 on 2024-06-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='inage',
            new_name='image',
        ),
    ]
